#!/usr/bin/env python3
"""
Parse dbCAN output and create HUMAnN utility mapping file for CAZy families.

This script processes dbCAN overview.txt files (generated by dbcan_cazy_build.sh)
and creates a tab-separated mapping file where each line contains:
    CAZy_family_ID<TAB>UniRef90_ID1<TAB>UniRef90_ID2<TAB>...

The output format matches HUMAnN utility mapping files (e.g., map_cazy_uniref90.txt).

Usage:
    python parse_dbcan_to_humann_map.py --input <overview_file> --output <output.tsv.gz>
    
Input format (dbCAN overview.txt):
    Gene ID    EC#    HMMER    dbCAN_sub    DIAMOND    Signalp    ...
    UniRef90_A0A1U8QIA6    -    CBM1(55-193)    -    CBM1    No    ...
    
Output format:
    CBM1<TAB>UniRef90_A0A1U8QIA6<TAB>UniRef90_A2Q7T5<TAB>...
    GH5<TAB>UniRef90_B2AAQ9<TAB>UniRef90_B2AB32<TAB>...
"""

import argparse
import gzip
import sys
from collections import defaultdict
from pathlib import Path
import re


def parse_dbcan_overview(overview_file):
    """
    Parse dbCAN overview.txt file and extract CAZy family annotations.
    
    Args:
        overview_file: Path to dbCAN overview.txt file
        
    Returns:
        dict: Dictionary mapping CAZy families to sets of UniRef90 IDs
    """
    cazy_map = defaultdict(set)
    
    # Handle both gzipped and plain text files
    if str(overview_file).endswith('.gz'):
        open_func = gzip.open
        mode = 'rt'
    else:
        open_func = open
        mode = 'r'
    
    with open_func(overview_file, mode) as f:
        # Skip header line
        header = f.readline()
        
        # Expected columns (may vary by dbCAN version):
        # Gene ID, EC#, HMMER, dbCAN_sub, DIAMOND, Signalp, ...
        # We'll look for CAZy annotations in HMMER, dbCAN_sub, and DIAMOND columns
        
        for line_num, line in enumerate(f, start=2):
            line = line.strip()
            if not line:
                continue
                
            fields = line.split('\t')
            if len(fields) < 5:
                print(f"Warning: Line {line_num} has fewer than 5 fields, skipping", file=sys.stderr)
                continue
            
            gene_id = fields[0]
            
            # Extract UniRef90 ID from gene ID
            # Gene ID format: UniRef90_A0A1U8QIA6
            if not gene_id.startswith('UniRef90_'):
                continue
            
            uniref_id = gene_id
            
            # Collect all CAZy annotations from different columns
            cazy_annotations = set()
            
            # Column 2: HMMER - format: "CBM1(55-193)" or "GH5+CBM2"
            hmmer = fields[2] if len(fields) > 2 else '-'
            if hmmer != '-':
                cazy_annotations.update(extract_cazy_families(hmmer))
            
            # Column 3: dbCAN_sub
            dbcan_sub = fields[3] if len(fields) > 3 else '-'
            if dbcan_sub != '-':
                cazy_annotations.update(extract_cazy_families(dbcan_sub))
            
            # Column 4: DIAMOND
            diamond = fields[4] if len(fields) > 4 else '-'
            if diamond != '-':
                cazy_annotations.update(extract_cazy_families(diamond))
            
            # Add this UniRef90 ID to all associated CAZy families
            for cazy_family in cazy_annotations:
                cazy_map[cazy_family].add(uniref_id)
    
    return cazy_map


def extract_cazy_families(annotation_string):
    """
    Extract CAZy family names from annotation strings.
    
    Handles formats like:
        - "CBM1(55-193)" -> ["CBM1"]
        - "GH5+CBM2" -> ["GH5", "CBM2"]
        - "GH5_1" -> ["GH5"]
        - "GT2_3" -> ["GT2"]
    
    Args:
        annotation_string: String containing CAZy annotations
        
    Returns:
        set: Set of CAZy family names
    """
    families = set()
    
    # Remove coordinate information: (55-193)
    annotation_string = re.sub(r'\(\d+-\d+\)', '', annotation_string)
    
    # Split on + or | or comma
    parts = re.split(r'[+|,]', annotation_string)
    
    for part in parts:
        part = part.strip()
        if not part or part == '-':
            continue
        
        # Extract CAZy family (letters followed by numbers)
        # Match patterns like: GH5, CBM1, GT2, PL3, CE4, AA1, etc.
        match = re.match(r'^([A-Z]+\d+)', part)
        if match:
            families.add(match.group(1))
    
    return families


def write_humann_mapping(cazy_map, output_file):
    """
    Write CAZy to UniRef90 mapping in HUMAnN format.
    
    Args:
        cazy_map: Dictionary mapping CAZy families to sets of UniRef90 IDs
        output_file: Path to output file (will be gzipped)
    """
    # Sort CAZy families for consistent output
    sorted_families = sorted(cazy_map.keys())
    
    with gzip.open(output_file, 'wt') as f:
        for family in sorted_families:
            uniref_ids = sorted(cazy_map[family])
            # Format: FAMILY<TAB>ID1<TAB>ID2<TAB>...
            line = family + '\t' + '\t'.join(uniref_ids) + '\n'
            f.write(line)


def main():
    parser = argparse.ArgumentParser(
        description='Parse dbCAN output and create HUMAnN CAZy utility mapping file',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    
    parser.add_argument(
        '-i', '--input',
        required=True,
        type=Path,
        help='Input dbCAN overview.txt file (can be gzipped)'
    )
    
    parser.add_argument(
        '-o', '--output',
        required=True,
        type=Path,
        help='Output mapping file (will be gzipped, e.g., map_cazy_uniref90.txt.gz)'
    )
    
    parser.add_argument(
        '--min-members',
        type=int,
        default=1,
        help='Minimum number of UniRef90 IDs required for a CAZy family (default: 1)'
    )
    
    args = parser.parse_args()
    
    # Check input file exists
    if not args.input.exists():
        print(f"Error: Input file not found: {args.input}", file=sys.stderr)
        sys.exit(1)
    
    # Ensure output has .gz extension
    if not str(args.output).endswith('.gz'):
        output_file = Path(str(args.output) + '.gz')
        print(f"Note: Adding .gz extension to output file: {output_file}", file=sys.stderr)
    else:
        output_file = args.output
    
    # Parse dbCAN overview file
    print(f"Parsing dbCAN overview file: {args.input}", file=sys.stderr)
    cazy_map = parse_dbcan_overview(args.input)
    
    # Filter by minimum members
    if args.min_members > 1:
        before = len(cazy_map)
        cazy_map = {
            family: ids 
            for family, ids in cazy_map.items() 
            if len(ids) >= args.min_members
        }
        after = len(cazy_map)
        print(f"Filtered CAZy families: {before} -> {after} (min_members={args.min_members})", 
              file=sys.stderr)
    
    # Report statistics
    total_families = len(cazy_map)
    total_uniref_ids = sum(len(ids) for ids in cazy_map.values())
    print(f"Found {total_families} CAZy families with {total_uniref_ids} total annotations", 
          file=sys.stderr)
    
    # Show top 10 families by member count
    print("\nTop 10 CAZy families by member count:", file=sys.stderr)
    sorted_by_count = sorted(cazy_map.items(), key=lambda x: len(x[1]), reverse=True)
    for family, ids in sorted_by_count[:10]:
        print(f"  {family}: {len(ids)} members", file=sys.stderr)
    
    # Write output
    print(f"\nWriting HUMAnN mapping file: {output_file}", file=sys.stderr)
    write_humann_mapping(cazy_map, output_file)
    
    print(f"Done! Output written to: {output_file}", file=sys.stderr)


if __name__ == '__main__':
    main()
